class Mads:

    mlb1 = ['Today, my fabulous camp group went to a(an) 1 amusement park. It was a fun park with lots of cool 2 and enjoyable play structures. When we got there, my kind counselor shouted loudly, \"Everybody off the 3.\" We all pushed out in a terrible hurry. My counselor handed out yellow tickets, and we scurried in. I was so excited! I couldn\'t figure out what exciting thing to do first. I saw a scary roller coaster I really liked so, I 4 ran over to get in the long line that had about 5 people in it. When I finally got on the roller coaster I was 6. In fact I was so nervous my two knees were knocking together. This was the 7 ride I had ever been on! In about two minutes I heard the crank and grinding of the gears. That’s when the ride began! When I got to the bottom, I was a little 8 but I was proud of myself. The rest of the day went 9. It was a(n) * day at the fun park'
    ]
    mlb3 = ['When I go to the arcade with my 1 there are lots of games to play. I spend lots of time there with my friends. In the game X-Men you can be different 2. The point of the game is to 3 every robot. You also need to save people. Then you can go to the next level. In the game Star Wars you are Luke Skywalker and you try to destroy every 4. In a car racing/motorcycle racing game you need to beat every computerized vehicle that you are 5 against. There are a whole lot of other cool games. When you play some games you win 6 for certain scores. Once you\'re done you can cash in your tickets to get a big 7. You can save your 8 for another time. When I went to this arcade I didn\'t believe how much fun it would be. So far I have had a lot of fun every time I\'ve been to this great arcade! '
    ]

    mlb2 = ['Today I went to the zoo. I saw a(n) 1 2 jumping up and down in its tree. He 4 5 through the large tunnel that led to i6 7. I got some peanuts and passed them through the cage to a gigantic gray 8 towering above my head. Feeding that animal made me hungry. I went to get a 8 scoop of ice cream. It filled my stomach. Afterwards I had to 9 * to catch our bus. When I got home I & my mom for a ^ day at the zoo'

    ]

    mlb4 = ['One very nice morning near the end of summer, my mother woke me up at 4:00 A.M. and said, \"Wake up and smell the grass, sleepy head! Today is your first day of school and you can\'t be late." I groaned in my bed for twenty seconds, but eventually I got dressed. I wore a blue and white striped, long sleeve 2 with a collar on it, a red tie, dark gray pants, white socks, black shoes, and a(n) 1 hat. In ten minutes I made lunch and ate my breakfast. 3 minutes later, the bus came. A few minutes later, I was at school. In school, I met two really 4 kids. All of us became friends very fast. That day we had Science, and luckily my friends and I were at the same 5. My friends\' names are 6 and 7. In Math we weren\'t together, and that really bugged me. We learned what 8 were, and when to use them. At snack and recess, we played a game together. It was extremely fun. At P. E., we were 9 off of the ropes onto'

    ]